version: "3.3"
services:

  #######################################################
  #  Rabbitmq
  #######################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - crawler

  mongodb:
    container_name: mongodb
    image: mongo:7
    restart: always
    ports:
        - '27017:27017'
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
        - MONGO_INITDB_DATABASE=crawler
    volumes:
      - ./deployments/docker-compose/mongodb:/data/db
    networks:
        - crawler


      #######################################################
      #  Jaeger
      #######################################################
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: always
    networks:
      - crawler
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686


networks:
  crawler:




